spring:
  application:
    name: auth-service

server:
  port: 8081

app:
  security:
    mode: jwt
    jwt:
      issuer: auth-service
      secret: demo-jwt-secret-please-change-in-production-32+chars
      access-token-ttl: 30m

management:
  endpoints:
    web:
      exposure:
        include: health,info
  tracing:
    sampling:
      probability: 1.0
  otlp:
    tracing:
      endpoint: http://localhost:4318/v1/traces
