spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://localhost:8081
          predicates:
            - Path=/auth/**
        - id: order-service
          uri: http://localhost:8082
          predicates:
            - Path=/orders/**
        - id: inventory-service
          uri: http://localhost:8083
          predicates:
            - Path=/inventory/**

server:
  port: 8080

app:
  security:
    mode: ${SECURITY_MODE:jwt}
    jwt:
      issuer: auth-service
      secret: demo-jwt-secret-please-change-in-production-32+chars
    passport:
      issuer: gateway-service
      secret: demo-passport-secret-please-change-internal-only-32+chars
      ttl: 30s
      header-name: X-Passport

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
  tracing:
    sampling:
      probability: 1.0
  otlp:
    tracing:
      endpoint: http://localhost:4318/v1/traces
